### ISSUE TITLE
Passing env var for url isn't working as expected

### ISSUE THREAD

**Issue by bfarayev** [walrusai/cli#6]
I'm trying to use this file first without setting any env var in my shell:

```
$ cat test.yml

---
name: 'Sample Test'
url: ':domain:'
variables:
  domain: $DOMAIN
instructions:
  - Click "Best Sellers"
```

this returns: `unknown environment variable - $DOMAIN`, which looks fine. Then I set the DOMAIN env var and run the test again.

```
$ export DOMAIN=https://www.amazon.com/
$ walrus "-a" "***" "-f" "test.yml"
```
I get 
```
Successes: 0
Failures: 1
{
  name: 'Sample Test',
  success: false,
  error: '"url" must be a valid uri'
}
```
It's hard to work around this issue right now and it's blocking us from taking env vars from CI environments.

**Comment by akshaynathan** [comment]
Hi Bakhtiyar, thanks for reporting, we are fixing this upstream, will update here when this is done.

**Comment by akshaynathan** [comment]
@bfarayev, this should be fixed now, validated by running the example you provided.

**Comment by bfarayev** [comment]
hi @akshaynathan thanks for quick fix. I can also confirm that it's working as expected now. 👍
